# Generated by Django 6.0 on 2026-01-09 17:12

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom')),
                ('withdrawal_fee_rate', models.PositiveIntegerField(help_text='Pourcentage de frais sur les retraits (ex: 2 pour 2%)', verbose_name='Taux de frais de retrait (%)')),
            ],
            options={
                'verbose_name': 'Plateforme',
                'verbose_name_plural': 'Plateformes',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('phone', models.CharField(max_length=20, unique=True, verbose_name='Téléphone')),
                ('gender', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin'), ('O', 'Autre')], max_length=10, verbose_name='Genre')),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('ACTIVE', 'Actif'), ('SUSPENDED', 'Suspendu')], default='PENDING', max_length=10, verbose_name='Statut')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Compte vérifié')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
                'ordering': ['-date_joined'],
            },
        ),
        migrations.CreateModel(
            name='VirtualAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('owner_type', models.CharField(choices=[('USER', 'Utilisateur'), ('PLATFORM', 'Plateforme')], default='USER', max_length=10, verbose_name='Type de propriétaire')),
                ('balance', models.BigIntegerField(default=0, verbose_name='Solde')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('platform', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='virtual_account', to='money_transfer.platform', verbose_name='Plateforme')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='virtual_account', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Compte virtuel',
                'verbose_name_plural': 'Comptes virtuels',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('reference', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Référence')),
                ('type', models.CharField(choices=[('DEPOSIT', 'Dépôt'), ('TRANSFER', 'Transfert'), ('WITHDRAWAL', 'Retrait'), ('FEE', 'Frais')], max_length=20, verbose_name='Type')),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('SUCCESS', 'Réussie'), ('FAILED', 'Échouée')], default='PENDING', max_length=10, verbose_name='Statut')),
                ('amount', models.PositiveBigIntegerField(help_text='Montant initial de la transaction', verbose_name='Montant brut')),
                ('fee', models.PositiveBigIntegerField(default=0, help_text='Frais appliqués (uniquement pour retrait)', verbose_name='Frais')),
                ('net_amount', models.PositiveBigIntegerField(help_text='Montant réellement transféré (amount - fee)', verbose_name='Montant net')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('receiver_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='received_transactions', to='money_transfer.virtualaccount', verbose_name='Compte récepteur')),
                ('sender_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sent_transactions', to='money_transfer.virtualaccount', verbose_name='Compte émetteur')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6, verbose_name='Code')),
                ('otp_type', models.CharField(choices=[('ACCOUNT_VALIDATION', 'Validation de compte'), ('WITHDRAWAL', "Retrait d'argent")], max_length=30, verbose_name='Type')),
                ('is_used', models.BooleanField(default=False, verbose_name='Utilisé')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('expires_at', models.DateTimeField(verbose_name='Expire le')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otps', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'OTP',
                'verbose_name_plural': 'OTPs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'otp_type', 'is_used'], name='money_trans_user_id_879245_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='virtualaccount',
            index=models.Index(fields=['owner_type', 'is_active'], name='money_trans_owner_t_3941ab_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['reference'], name='money_trans_referen_eb477f_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['sender_account', 'status'], name='money_trans_sender__7bd4f6_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['receiver_account', 'status'], name='money_trans_receive_c8b3bb_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['-created_at'], name='money_trans_created_75cec7_idx'),
        ),
    ]
